version: '3'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    container_name: marketDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=peopledb
    volumes:
      - peopledb-data:/var/lib/postgresql/data

  backend:
    image: people_backend
    container_name: backend
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=peopledb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

volumes:
  peopledb-data:
